#服务器配置
server:
  port: 8101

wechat:
  AppID: wx65b4991350589e3b
  AppSecret: 2fea01e1e7e9739651cdd8a0c0026186

qiniu:
  accesskey: w4oGfWxk1HCqIU3mvv91WQ09YwPe45S_nVLW2FJT
  secretkey: 4lcLeZJTu-xCM0TbX6X_wDDKEjknL6r-BXJclL_G
  bucketname: ben286
  buckethostname: qiniu.ben286.top

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://pgrk.wizzstudio.com:3333/pgrk?serverTimezone=Asia/Shanghai&useSSL=false
    username: "pgrk"
    password: "wizz.pgrk"


#本地配置
#server:
#  port: 8080
#
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/pgrk?serverTimezone=Asia/Shanghai&useSSL=false
#    username: "root"
#    password: "000326"
#
#
#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: com.wizzstudio.languagerank.config.MysqlConfig
#    open-in-view: true


# redis:
#  host: 47.105.192.87
#  port: 6666
#  password: xdwizzno1
##  timeout: 3000
#  database:
#    moreLanguageInformation: 0
#  jedis:
#     pool:
##      max-active: 8
#      max-idle: 8
##      max-wait: -1
#      min-idle: 0